USE [DB37]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE ApprovalStatus
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(50)


CONSTRAINT ApprovalStatus_pk PRIMARY KEY (Id)
);


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE ActiveStatus
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(50),

CONSTRAINT ActiveStatus_pk PRIMARY KEY (Id)
);


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE Students
(
Id INT IDENTITY(1,1) NOT NULL,
FirstName NVARCHAR(50),
LastName NVARCHAR(50),
RegistrationNumber NVARCHAR(50),
Username NVARCHAR(50),
StdPassword NVARCHAR(30),
CNIC NVARCHAR(15),
ApprovalStatusId INT,
ActiveStatusId INT,
CONSTRAINT Students_pk PRIMARY KEY (Id),
FOREIGN KEY(ApprovalStatusId) REFERENCES ApprovalStatus(Id) ON DELETE CASCADE,
FOREIGN KEY(ActiveStatusId) REFERENCES ActiveStatus(Id) ON DELETE CASCADE

);

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Parents
(
Id INT IDENTITY(1,1) NOT NULL,
FirstName NVARCHAR(50),
LastName NVARCHAR(50),
PhoneNumber NVARCHAR(50),
PrntPassword NVARCHAR(30),
CNIC NVARCHAR(15),
ApprovalStatusId INT,
MailAddress NVARCHAR(50),
FOREIGN KEY(ApprovalStatusId) REFERENCES ApprovalStatus(Id) ON DELETE CASCADE,
CONSTRAINT Parents_pk PRIMARY KEY (Id)
);


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Class
(
Id INT IDENTITY(1,1) NOT NULL,
Section NVARCHAR(50),

CONSTRAINT Class_pk PRIMARY KEY (Id)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Subjects
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(50),

CONSTRAINT Subjects_pk PRIMARY KEY (Id)

);

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE ClassSubject
(
ClassId INT,
SubjectId INT,
FOREIGN KEY(ClassId) REFERENCES Class(Id) ON DELETE CASCADE,
FOREIGN KEY(SubjectId) REFERENCES Subjects(Id) ON DELETE CASCADE,
CONSTRAINT ClassSubject_pk PRIMARY KEY (ClassId, SubjectId)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE StudentClass
(
ClassId INT,
StudentId INT,

FOREIGN KEY(ClassId) REFERENCES Class(Id) ON DELETE CASCADE,
FOREIGN KEY(StudentId) REFERENCES Students(Id) ON DELETE CASCADE,

CONSTRAINT StudentClass_pk PRIMARY KEY (ClassId,StudentId)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE ParentStudent
(
ParentId INT,
StudentId INT,

FOREIGN KEY(StudentId) REFERENCES Students(Id),
FOREIGN KEY(ParentId) REFERENCES Parents(Id),
CONSTRAINT ParentStudent_pk PRIMARY KEY (ParentId, StudentId)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE SchoolEvents
(
Id INT IDENTITY(1,1) NOT NULL,
Title NVARCHAR(50),
EventDescription NVARCHAR(MAX),
EventDate DateTime,
StartTime DateTime,
EndTime DateTime,
Contact NVARCHAR(20),
Charges NVARCHAR(20),


CONSTRAINT SchoolEvents_pk PRIMARY KEY (Id)
);





SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE AttendanceStatus
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(30)


CONSTRAINT AttendanceStatus_pk PRIMARY KEY (Id)
);





SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE AttendanceMarking
(
StudentId INT,
AttendanceDate DateTime,
AttendanceStatusId INT,

FOREIGN KEY(StudentId) REFERENCES Students(Id) ON DELETE CASCADE,
FOREIGN KEY(AttendanceStatusId) REFERENCES AttendanceStatus(Id) ON DELETE CASCADE,
CONSTRAINT AttendanceMarking_pk PRIMARY KEY (StudentId,AttendanceDate)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Adminstrator
(
Id INT IDENTITY(1,1) NOT NULL,
Username NVARCHAR(50),
Email NVARCHAR(50),
PhoneNumber NVARCHAR(50),
AdminPassword NVARCHAR(30),
CNIC NVARCHAR(20),


CONSTRAINT Administrator_pk PRIMARY KEY (Id, Username)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Leaves
(
Id INT IDENTITY(1,1) NOT NULL,
ParentId INT,
StudentId INT,
LeaveDescription NVARCHAR(MAX),
DateFrom DATETIME,
DateEnd DATETIME,
ApprovalStatusId INT ,
FOREIGN KEY(ParentId) REFERENCES Parents(Id) ,
FOREIGN KEY(StudentId) REFERENCES Students(Id) ,
CONSTRAINT Leaves_pk PRIMARY KEY (Id)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE StudentLeft
(
StudentId INT,
DateLeft DATETIME,
FOREIGN KEY(StudentId) REFERENCES Students(Id) ON DELETE CASCADE,

CONSTRAINT StudentLeft_pk PRIMARY KEY (StudentId)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TimeTable
(
WeeksDay NVARCHAR(30),
ClassId INT,
SubjectId INT,
LectureTime TIME,
FOREIGN KEY(ClassId) REFERENCES Class(Id) ON DELETE CASCADE,
FOREIGN KEY(SubjectId) REFERENCES Subjects(Id) ON DELETE CASCADE,
CONSTRAINT TimeTable_pk PRIMARY KEY (WeeksDay, ClassId, SubjectId)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Terms
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(50)
CONSTRAINT Terms_pk PRIMARY KEY (Id)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Markings
(
ClassId INT,
SubjectId INT,
StudentId INT,
TotalMarks FLOAT,
ObtainedMarks FLOAT,
TermId INT

CONSTRAINT Markings_pk PRIMARY KEY (ClassId, StudentId, SubjectId, TermId),
FOREIGN KEY(ClassId) REFERENCES Class(Id) ON DELETE CASCADE,
FOREIGN KEY(SubjectId) REFERENCES Subjects(Id) ON DELETE CASCADE,
FOREIGN KEY(StudentId) REFERENCES Students(Id) ON DELETE CASCADE,
FOREIGN KEY(TermId) REFERENCES Terms(Id) ON DELETE CASCADE
);

