USE [DB37]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE ApprovalStatustbl
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(50)


CONSTRAINT ApprovalStatustbl_pk PRIMARY KEY (Id)
);


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE ActiveStatustbl
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(50),

CONSTRAINT ActiveStatustbl_pk PRIMARY KEY (Id)
);


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE Studentstbl
(
Id INT IDENTITY(1,1) NOT NULL,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
RegistrationNumber NVARCHAR(50) NOT NULL,
Username NVARCHAR(50) NOT NULL,
StdPassword NVARCHAR(30) NOT NULL,
CNIC NVARCHAR(15) NOT NULL,
ApprovalStatusId INT NOT NULL,
ActiveStatusId INT NOT NULL,
CONSTRAINT Studentstbl_pk PRIMARY KEY (Id),
FOREIGN KEY(ApprovalStatusId) REFERENCES ApprovalStatustbl(Id) ON DELETE CASCADE,
FOREIGN KEY(ActiveStatusId) REFERENCES ActiveStatustbl(Id) ON DELETE CASCADE

);

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Parentstbl
(
Id INT IDENTITY(1,1) NOT NULL,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
PhoneNumber NVARCHAR(50) NOT NULL,
PrntPassword NVARCHAR(30) NOT NULL,
CNIC NVARCHAR(15) NOT NULL,
ApprovalStatusId INT NOT NULL,
MailAddress NVARCHAR(50) NOT NULL,
FOREIGN KEY(ApprovalStatusId) REFERENCES ApprovalStatustbl(Id) ON DELETE CASCADE,
CONSTRAINT Parentstbl_pk PRIMARY KEY (Id)
);


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Classtbl
(
Id INT IDENTITY(1,1) NOT NULL,
Section NVARCHAR(50) NOT NULL,

CONSTRAINT Classtbl_pk PRIMARY KEY (Id)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Subjectstbl
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(50) NOT NULL,

CONSTRAINT Subjectstbl_pk PRIMARY KEY (Id)

);

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE ClassSubjecttbl
(
Id INT IDENTITY(1,1) NOT NULL,
ClassId INT NOT NULL,
SubjectId INT NOT NULL,
FOREIGN KEY(ClassId) REFERENCES Classtbl(Id) ON DELETE CASCADE,
FOREIGN KEY(SubjectId) REFERENCES Subjectstbl(Id) ON DELETE CASCADE,
CONSTRAINT ClassSubjecttbl_pk PRIMARY KEY (Id)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE StudentClasstbl
(
Id INT IDENTITY(1,1) NOT NULL,
ClassId INT NOT NULL,
StudentId INT NOT NULL,

FOREIGN KEY(ClassId) REFERENCES Classtbl(Id) ON DELETE CASCADE,
FOREIGN KEY(StudentId) REFERENCES Studentstbl(Id) ON DELETE CASCADE,

CONSTRAINT StudentClasstbl_pk PRIMARY KEY (Id)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE ParentStudenttbl
(
Id INT IDENTITY(1,1) NOT NULL,
ParentId INT NOT NULL,
StudentId INT NOT NULL,

FOREIGN KEY(StudentId) REFERENCES Studentstbl(Id) ON DELETE CASCADE,
FOREIGN KEY(ParentId) REFERENCES Parentstbl(Id),
CONSTRAINT ParentStudenttbl_pk PRIMARY KEY (Id)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE SchoolEventstbl
(
Id INT IDENTITY(1,1) NOT NULL,
Title NVARCHAR(50) NOT NULL,
EventDescription NVARCHAR(MAX) NOT NULL,
EventDate DateTime NOT NULL,
StartTime DateTime NOT NULL,
EndTime DateTime NOT NULL,
Contact NVARCHAR(20) NOT NULL,
Charges NVARCHAR(20) NOT NULL,


CONSTRAINT SchoolEventstbl_pk PRIMARY KEY (Id)
);





SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE AttendanceStatustbl
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(30) NOT NULL


CONSTRAINT AttendanceStatustbl_pk PRIMARY KEY (Id)
);





SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE AttendanceMarkingtbl
(
StudentId INT NOT NULL,
AttendanceDate DateTime NOT NULL,
AttendanceStatusId INT NOT NULL,

FOREIGN KEY(StudentId) REFERENCES Studentstbl(Id) ON DELETE CASCADE,
FOREIGN KEY(AttendanceStatusId) REFERENCES AttendanceStatustbl(Id) ON DELETE CASCADE,
CONSTRAINT AttendanceMarkingtbl_pk PRIMARY KEY (StudentId,AttendanceDate)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Adminstratortbl
(
Id INT IDENTITY(1,1) NOT NULL,
Username NVARCHAR(50) NOT NULL,
Email NVARCHAR(50) NOT NULL,
PhoneNumber NVARCHAR(50) NOT NULL,
AdminPassword NVARCHAR(30) NOT NULL,
CNIC NVARCHAR(20) NOT NULL,


CONSTRAINT Administratortbl_pk PRIMARY KEY (Id, Username)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Leavestbl
(
Id INT IDENTITY(1,1) NOT NULL,
ParentId INT NOT NULL,
StudentId INT NOT NULL,
LeaveDescription NVARCHAR(MAX) NOT NULL,
DateFrom DATETIME NOT NULL,
DateEnd DATETIME NOT NULL,
ApprovalStatusId INT  NOT NULL,
FOREIGN KEY(ParentId) REFERENCES Parentstbl(Id),
FOREIGN KEY(StudentId) REFERENCES Studentstbl(Id)  ON DELETE CASCADE,
CONSTRAINT Leavestbl_pk PRIMARY KEY (Id)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE StudentLefttbl
(
StudentId INT NOT NULL,
DateLeft DATETIME NOT NULL,
FOREIGN KEY(StudentId) REFERENCES Studentstbl(Id) ON DELETE CASCADE,

CONSTRAINT StudentLefttbl_pk PRIMARY KEY (StudentId)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TimeTabletbl
(
WeeksDay NVARCHAR(30) NOT NULL,
ClassId INT NOT NULL,
SubjectId INT NOT NULL,
LectureTime TIME NOT NULL,
FOREIGN KEY(ClassId) REFERENCES Classtbl(Id) ON DELETE CASCADE,
FOREIGN KEY(SubjectId) REFERENCES Subjectstbl(Id) ON DELETE CASCADE,
CONSTRAINT TimeTabletbl_pk PRIMARY KEY (WeeksDay, ClassId, SubjectId)
);



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Termstbl
(
Id INT IDENTITY(1,1) NOT NULL,
Name NVARCHAR(50) NOT NULL,
CONSTRAINT Termstbl_pk PRIMARY KEY (Id)
);




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Markingstbl
(
ClassId INT  NOT NULL,
SubjectId INT NOT NULL,
StudentId INT NOT NULL,
TotalMarks FLOAT NOT NULL,
ObtainedMarks FLOAT NOT NULL,
TermId INT NOT NULL,

CONSTRAINT Markingstbl_pk PRIMARY KEY (ClassId, StudentId, SubjectId, TermId),
FOREIGN KEY(ClassId) REFERENCES Classtbl(Id) ON DELETE CASCADE,
FOREIGN KEY(SubjectId) REFERENCES Subjectstbl(Id) ON DELETE CASCADE,
FOREIGN KEY(StudentId) REFERENCES Studentstbl(Id) ON DELETE CASCADE,
FOREIGN KEY(TermId) REFERENCES Termstbl(Id) ON DELETE CASCADE
);


INSERT INTO Adminstratortbl("Username", Email, PhoneNumber, AdminPassword, CNIC)
VALUES ('Admin', 'admin@gmail.com', '03200498942', '123', '1234567890')

INSERT INTO AttendanceStatustbl(Name) VALUES ('Present')
INSERT INTO AttendanceStatustbl(Name) VALUES ('Absent')
INSERT INTO AttendanceStatustbl(Name) VALUES ('Leave')

INSERT INTO ApprovalStatustbl(Name) VALUES ('pending')
INSERT INTO ApprovalStatustbl(Name) VALUES ('approved')

INSERT INTO ActiveStatustbl(Name) VALUES ('Inavtice')
INSERT INTO ActiveStatustbl(Name) VALUES ('Active')


INSERT INTO Termstbl(Name) VALUES ('Term1')
INSERT INTO Termstbl(Name) VALUES ('Term2')
INSERT INTO Termstbl(Name) VALUES ('Term3')