//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leavestbl
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string LeaveDescription { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> ApprovalStatusId { get; set; }
    
        public virtual Parentstbl Parentstbl { get; set; }
        public virtual Studentstbl Studentstbl { get; set; }
    }
}
