//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB37Entities : DbContext
    {
        public DB37Entities()
            : base("name=DB37Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveStatustbl> ActiveStatustbls { get; set; }
        public virtual DbSet<Adminstratortbl> Adminstratortbls { get; set; }
        public virtual DbSet<ApprovalStatustbl> ApprovalStatustbls { get; set; }
        public virtual DbSet<AttendanceMarkingtbl> AttendanceMarkingtbls { get; set; }
        public virtual DbSet<AttendanceStatustbl> AttendanceStatustbls { get; set; }
        public virtual DbSet<ClassSubjecttbl> ClassSubjecttbls { get; set; }
        public virtual DbSet<Classtbl> Classtbls { get; set; }
        public virtual DbSet<Leavestbl> Leavestbls { get; set; }
        public virtual DbSet<Markingstbl> Markingstbls { get; set; }
        public virtual DbSet<Parentstbl> Parentstbls { get; set; }
        public virtual DbSet<ParentStudenttbl> ParentStudenttbls { get; set; }
        public virtual DbSet<SchoolEventstbl> SchoolEventstbls { get; set; }
        public virtual DbSet<StudentClasstbl> StudentClasstbls { get; set; }
        public virtual DbSet<StudentLefttbl> StudentLefttbls { get; set; }
        public virtual DbSet<Studentstbl> Studentstbls { get; set; }
        public virtual DbSet<Subjectstbl> Subjectstbls { get; set; }
        public virtual DbSet<Termstbl> Termstbls { get; set; }
        public virtual DbSet<TimeTabletbl> TimeTabletbls { get; set; }
    }
}
